---
roles:
  - name: ewc-ansible-role-ipa-server-1.1
    src: https://github.com/ewcloud/ewc-ansible-role-ipa-server.git
    version: 1.1.0

  - name: ewc-ansible-role-ipa-client-enroll-1.2
    src: https://github.com/ewcloud/ewc-ansible-role-ipa-client-enroll.git
    version: 1.2.0

  - name: ewc-ansible-role-ssh-bastion-1.5
    src: https://github.com/ewcloud/ewc-ansible-role-ssh-bastion.git
    version: 1.5.2

  - name: ewc-ansible-role-remote-desktop-1.3
    src: https://github.com/ewcloud/ewc-ansible-role-remote-desktop.git
    version: 1.3.2
