---
roles:
  - name: ewc-ansible-role-update-system
    src: https://github.com/ewcloud/ewc-ansible-role-update-system.git
    version: 1.0.0

  - name: ewc-ansible-role-conda-1.1
    src: https://github.com/ewcloud/ewc-ansible-role-conda.git
    version: 1.1.0